import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Gregor Cox | Software Engineer",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "/icons/favicon-32x32.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "192x192",
      url: "/icons/favicon-192x192.png",
    },
    {
      rel: "apple-touch-icon",
      sizes: "180x180",
      url: "/icons/favicon-192x192.png",
    },
    { rel: "shortcut icon", url: "/icons/favicon.ico" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        <main>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
